/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2273bc91-4fc3-4d18-a101-48c4dcbb7f43",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_30tcV4ugQ",
    "aws_user_pools_web_client_id": "2t89evpisv0n6dv1h7cbl3fakn",
    "oauth": {}
};


export default awsmobile;
